### ISSUE TITLE
Tutorial how to install and use it.

### ISSUE THREAD

**Issue by ingnelson** [conor19w/Predicting-the-Price-Movements-of-Bitcoin#1]
Hello. 
Can you explain how to install it and use it , please . 
If it is possible create a example. Please.

**Comment by conor19w** [comment]
Hey,
This was for my final year thesis, I have a presentation video running through it which I can link if you'd like.
But really this was just to get my foot in the door when it comes to machine learning it was just a fun project for a classification problem, In reality the system wouldn't be profitable when you take into account the trading fees.
If you are interested in Technical Analysis/ Crypto Trading bots you should check out my other repo https://github.com/conor19w/Binance-Futures-Trading-Bot with this you can use the ready made Technical Analysis strategies and paper trade/ actually trade (at your own risk that is). And you can also implement your own trading strategies as functions in the TradingStrats.py file.
Thanks.

**Comment by conor19w** [comment]
Here is the two part video presentation if you are still interested:
https://drive.google.com/drive/folders/11Ui7YjzBHS9N2duAlOD1raOrjjVXpuEx?usp=sharing
